#pragma once

#include <cstddef>
#include <string>
#include <vector>

#include "microvllm/model_engine.hpp"
#include "microvllm/token_sink.hpp"
#include "microvllm/types.hpp"

namespace microvllm {

// The per-request generation state machine, independent of how it is driven.
//
// This is the piece that makes batching possible: a batched scheduler decodes many
// sequences in one forward pass, then advances each one *independently* -- each has its
// own position, its own stop strings, its own token budget, and finishes at its own
// time. Phase 1's single-request generator, Phase 3's static batching, and Phase 4's
// continuous batching all drive this same object, so the stop and accounting rules are
// defined (and tested) exactly once.
//
// Lifecycle:
//     SequenceState s(seq, spec, sink, engine.tokenize(spec.prompt, true));
//     decode(s.prefill_item())            -> GenStep
//     while (s.accept(engine, step))      // false => finished
//         decode(s.decode_item())         -> GenStep
//     s.finish();                         // flush tail + notify sink, exactly once
class SequenceState {
public:
    SequenceState(SeqId seq, RequestSpec spec, ITokenSink& sink, std::vector<Token> prompt);

    SequenceState(const SequenceState&)            = delete;
    SequenceState& operator=(const SequenceState&) = delete;

    // Prefill the whole prompt, sampling the first generated token from its last position.
    [[nodiscard]] BatchItem prefill_item() const;

    // Feed the most recently accepted token back in to produce the next one.
    [[nodiscard]] BatchItem decode_item() const;

    // Consume a sampled token: apply stop rules and accounting, streaming any text that
    // is now safe to emit. Returns true if the sequence needs another decode step, false
    // if it has finished (reason() is then set).
    [[nodiscard]] bool accept(IModelEngine& engine, const GenStep& step);

    // Flush any held-back tail where appropriate and deliver on_finish. Idempotent, so a
    // scheduler unwinding an error path cannot double-notify a sink.
    void finish();

    [[nodiscard]] SeqId seq() const { return seq_; }
    [[nodiscard]] bool finished() const { return finished_; }
    [[nodiscard]] FinishReason reason() const { return reason_; }
    [[nodiscard]] const Usage& usage() const { return usage_; }
    [[nodiscard]] const std::string& text() const { return text_; }

    // Mark the sequence as failed (backend error). finish() then reports it.
    void fail(std::string message);

private:
    void        flush_upto(std::size_t upto);
    void        stop_with(FinishReason reason);
    [[nodiscard]] std::size_t safe_prefix() const;

    // Position at which the pending token is fed back in. Derived rather than tracked:
    // the prompt occupies [0, n_prompt), and the k-th generated token (1-based) is fed
    // in at n_prompt + k - 1. Deriving it removes a whole class of off-by-one bugs when
    // sequences advance out of lockstep.
    [[nodiscard]] Pos feed_pos() const;

    SeqId              seq_;
    RequestSpec        spec_;
    ITokenSink&        sink_;
    std::vector<Token> prompt_;
    std::size_t        holdback_;  // bytes withheld so a stop string is never split

    Token        pending_ = 0;  // most recently accepted token, awaiting its decode
    std::string  text_;         // every generated byte
    std::size_t  emitted_ = 0;  // bytes already handed to sink.on_text
    Usage        usage_{};
    FinishReason reason_    = FinishReason::kUnset;
    bool         finished_  = false;
    bool         notified_  = false;
    std::string  error_;
};

}  // namespace microvllm
