#pragma once

#include <cstddef>
#include <span>
#include <string>
#include <string_view>
#include <vector>

#include "microvllm/model_engine.hpp"
#include "microvllm/token_sink.hpp"
#include "microvllm/types.hpp"

namespace microvllm {

// The per-request generation state machine, independent of how it is driven.
//
// This is the piece that makes batching possible: a batched scheduler decodes many
// sequences in one forward pass, then advances each one *independently* -- each has its
// own position, its own stop strings, its own token budget, and finishes at its own
// time. Phase 1's single-request generator, Phase 3's static batching, and Phase 4's
// continuous batching all drive this same object, so the stop and accounting rules are
// defined (and tested) exactly once.
//
// Lifecycle:
//     SequenceState s(seq, spec, sink, engine.tokenize(spec.prompt, true));
//     decode(s.prefill_item())            -> GenStep
//     while (s.accept(engine, step))      // false => finished
//         decode(s.decode_item())         -> GenStep
//     s.finish();                         // flush tail + notify sink, exactly once
class SequenceState {
public:
    SequenceState(SeqId seq, RequestSpec spec, ITokenSink& sink, std::vector<Token> prompt);

    SequenceState(const SequenceState&)            = delete;
    SequenceState& operator=(const SequenceState&) = delete;

    // Declare that the first `n_tokens` of the prompt are already in this sequence's KV
    // cache (inherited from a shared prefix), so prefill starts after them instead of at
    // zero. Must be called before the first prefill chunk.
    //
    // The count is recorded in Usage::cached_prompt_tokens, which is a *subset* of
    // prompt_tokens rather than an addition -- the tokens were still part of the request,
    // they just did not have to be recomputed.
    void adopt_cached_prefix(std::size_t n_tokens);

    // Prompt tokens not yet submitted to the engine. Zero once prefill is complete.
    [[nodiscard]] std::size_t prefill_remaining() const;

    // True once the whole prompt has been submitted, i.e. the sequence is decoding.
    [[nodiscard]] bool prefilling() const { return prefill_remaining() > 0; }

    // Take up to `budget` prompt tokens as the next prefill chunk, advancing internal
    // state. The returned item samples ONLY if this chunk completes the prompt -- an
    // intermediate chunk produces no token, it just populates KV cache.
    //
    // Chunking exists so a long prompt cannot stall a whole batch: submitting 512 prompt
    // tokens in one step would make every other sequence in that batch wait for it. The
    // cost is that sequence's own time-to-first-token, which is the tradeoff the
    // scheduler's chunk budget controls.
    [[nodiscard]] BatchItem take_prefill_chunk(std::size_t budget);

    // Prefill the whole prompt in one item, sampling the first generated token.
    // Equivalent to take_prefill_chunk(prefill_remaining()).
    [[nodiscard]] BatchItem prefill_item() { return take_prefill_chunk(prompt_.size()); }

    // Feed the most recently accepted token back in to produce the next one.
    [[nodiscard]] BatchItem decode_item() const;

    // Consume a sampled token: apply stop rules and accounting, streaming any text that
    // is now safe to emit. Returns true if the sequence needs another decode step, false
    // if it has finished (reason() is then set).
    [[nodiscard]] bool accept(IModelEngine& engine, const GenStep& step);

    // Flush any held-back tail where appropriate and deliver on_finish. Idempotent, so a
    // scheduler unwinding an error path cannot double-notify a sink.
    void finish();

    [[nodiscard]] SeqId seq() const { return seq_; }
    [[nodiscard]] std::span<const Token> prompt() const { return prompt_; }
    [[nodiscard]] bool finished() const { return finished_; }
    [[nodiscard]] FinishReason reason() const { return reason_; }
    [[nodiscard]] const Usage& usage() const { return usage_; }

    // Every generated byte, including any tail withheld by stop-string handling.
    [[nodiscard]] const std::string& text() const { return text_; }

    // The bytes actually delivered to the sink -- i.e. the response body. Differs from
    // text() when a stop string truncated the output: the suppressed tail was generated
    // but must never be returned.
    [[nodiscard]] std::string_view emitted_text() const {
        return std::string_view(text_).substr(0, emitted_);
    }

    [[nodiscard]] const std::string& error() const { return error_; }

    // Mark the sequence as failed. finish() then reports it via the sink's on_error.
    // `reason` distinguishes a backend fault (kError) from a client one such as a request
    // that cannot fit the context (kContextOverflow), which the server maps to 4xx.
    void fail(std::string message, FinishReason reason = FinishReason::kError);

private:
    void        flush_upto(std::size_t upto);
    void        stop_with(FinishReason reason);
    [[nodiscard]] std::size_t safe_prefix() const;

    // Position at which the pending token is fed back in. Derived rather than tracked:
    // the prompt occupies [0, n_prompt), and the k-th generated token (1-based) is fed
    // in at n_prompt + k - 1. Deriving it removes a whole class of off-by-one bugs when
    // sequences advance out of lockstep.
    [[nodiscard]] Pos feed_pos() const;

    SeqId              seq_;
    RequestSpec        spec_;
    ITokenSink&        sink_;
    std::vector<Token> prompt_;
    std::size_t        holdback_;  // bytes withheld so a stop string is never split

    std::size_t  prefilled_ = 0;  // prompt tokens already submitted to the engine
    Token        pending_   = 0;  // most recently accepted token, awaiting its decode
    std::string  text_;           // every generated byte
    std::size_t  emitted_ = 0;  // bytes already handed to sink.on_text
    Usage        usage_{};
    FinishReason reason_    = FinishReason::kUnset;
    bool         finished_  = false;
    bool         notified_  = false;
    std::string  error_;
};

}  // namespace microvllm
