#include "microvllm/generator.hpp"

#include <gtest/gtest.h>

#include <string>

#include "microvllm/collecting_sink.hpp"
#include "microvllm/mock_engine.hpp"

namespace microvllm {
namespace {

constexpr SeqId kSeq = 0;

RequestSpec req(std::string prompt, std::uint32_t max_tokens = 128,
                std::vector<std::string> stop = {}) {
    RequestSpec s;
    s.prompt     = std::move(prompt);
    s.max_tokens = max_tokens;
    s.stop       = std::move(stop);
    return s;
}

// CollectingSink holds an atomic and is intentionally non-movable, so extract a
// plain snapshot after running rather than returning the sink by value.
struct Result {
    std::string  text;
    FinishReason reason;
    Usage        usage;
};

Result run(const std::string& response, const RequestSpec& spec) {
    MockModelEngine engine(MockModelEngine::Config{.response = response});
    CollectingSink sink;
    generate_one(engine, kSeq, spec, sink);
    EXPECT_TRUE(sink.done());
    return Result{sink.text(), sink.reason(), sink.usage()};
}

TEST(Generator, GeneratesFullResponseAndStopsAtEos) {
    const Result r = run("Hello", req("hi"));
    EXPECT_EQ(r.text, "Hello");
    EXPECT_EQ(r.reason, FinishReason::kEos);
}

TEST(Generator, EmptyResponseYieldsEmptyOutput) {
    const Result r = run("", req("hi"));
    EXPECT_EQ(r.text, "");
    EXPECT_EQ(r.reason, FinishReason::kEos);
    EXPECT_EQ(r.usage.completion_tokens, 0U);
}

TEST(Generator, StopsAtMaxTokens) {
    const Result r = run("abcdef", req("hi", /*max_tokens=*/3));
    EXPECT_EQ(r.text, "abc");
    EXPECT_EQ(r.reason, FinishReason::kMaxTokens);
    EXPECT_EQ(r.usage.completion_tokens, 3U);
}

TEST(Generator, StopStringSingleCharTruncatesBeforeIt) {
    const Result r = run("abc", req("hi", 128, {"b"}));
    EXPECT_EQ(r.text, "a");
    EXPECT_EQ(r.reason, FinishReason::kStopString);
}

TEST(Generator, StopStringSpanningTokensTruncatesBeforeIt) {
    // Byte-level mock => each token is one char, so "o w" spans three tokens. The
    // holdback buffer must still find it and truncate at the right place.
    const Result r = run("Hello world", req("hi", 128, {"o w"}));
    EXPECT_EQ(r.text, "Hell");
    EXPECT_EQ(r.reason, FinishReason::kStopString);
}

TEST(Generator, StreamedDeltasEqualFinalTextWithStop) {
    // CollectingSink builds text() purely from on_text deltas, so a passing
    // truncation assertion here also proves the stream and the result agree.
    const Result r = run("stop here please", req("hi", 128, {" here"}));
    EXPECT_EQ(r.text, "stop");
    EXPECT_EQ(r.reason, FinishReason::kStopString);
}

TEST(Generator, EarliestStopWins) {
    const Result r = run("a-b-c", req("hi", 128, {"c", "-b"}));
    EXPECT_EQ(r.text, "a");  // "-b" at index 1 beats "c" at index 3
    EXPECT_EQ(r.reason, FinishReason::kStopString);
}

TEST(Generator, UsageCountsPromptAndCompletionTokens) {
    // Prompt "hi" tokenizes to [BOS, 'h', 'i'] = 3; response "abc" = 3 completion.
    const Result r = run("abc", req("hi"));
    EXPECT_EQ(r.usage.prompt_tokens, 3U);
    EXPECT_EQ(r.usage.completion_tokens, 3U);
    EXPECT_EQ(r.usage.total_tokens(), 6U);
}

TEST(Generator, CompletionCountIncludesStopTriggeringToken) {
    const Result r = run("abc", req("hi", 128, {"b"}));
    EXPECT_EQ(r.text, "a");
    EXPECT_EQ(r.usage.completion_tokens, 2U)
        << "'b' was generated by the model even though it is not in the output";
}

// Sink that reports cancellation once N text deltas have arrived.
class CancelAfter final : public ITokenSink {
public:
    explicit CancelAfter(int n) : remaining_(n) {}
    void on_text(std::string_view d) override {
        text_ += d;
        if (remaining_ > 0) {
            --remaining_;
        }
    }
    void on_finish(FinishReason r, const Usage&) override { reason_ = r; }
    void on_error(std::string_view) override {}
    [[nodiscard]] bool cancelled() const override { return remaining_ <= 0; }

    std::string  text_;
    FinishReason reason_ = FinishReason::kUnset;

private:
    int remaining_;
};

TEST(Generator, StopsWhenSinkCancels) {
    MockModelEngine engine(MockModelEngine::Config{.response = "abcdefgh"});
    CancelAfter sink(2);  // cancels after 2 deltas
    generate_one(engine, kSeq, req("hi"), sink);

    EXPECT_EQ(sink.reason_, FinishReason::kCancelled);
    EXPECT_LT(sink.text_.size(), 8U) << "should not have generated the whole response";
}

TEST(Generator, CallsFinishExactlyOnce) {
    struct CountingSink final : ITokenSink {
        void on_text(std::string_view) override {}
        void on_finish(FinishReason, const Usage&) override { ++finishes; }
        void on_error(std::string_view) override { ++errors; }
        [[nodiscard]] bool cancelled() const override { return false; }
        int finishes = 0;
        int errors   = 0;
    } sink;

    MockModelEngine engine(MockModelEngine::Config{.response = "hi"});
    generate_one(engine, kSeq, req("p"), sink);
    EXPECT_EQ(sink.finishes, 1);
    EXPECT_EQ(sink.errors, 0);
}

}  // namespace
}  // namespace microvllm
