#include "microvllm/generator.hpp"

#include <algorithm>
#include <array>
#include <cstddef>
#include <string>

namespace microvllm {
namespace {

// Earliest index at which any (non-empty) stop string occurs in `text`, or npos.
std::size_t earliest_stop(const std::string& text, const std::vector<std::string>& stops) {
    std::size_t best = std::string::npos;
    for (const std::string& s : stops) {
        if (s.empty()) {
            continue;
        }
        best = std::min(best, text.find(s));
    }
    return best;
}

// Longest stop string, which sets how many trailing bytes must be held back: a stop of
// length L can only start L-1 bytes before the current end, so holding back
// (max_stop - 1) bytes guarantees output is never emitted into a stop region.
std::size_t max_stop_len(const std::vector<std::string>& stops) {
    std::size_t m = 0;
    for (const std::string& s : stops) {
        m = std::max(m, s.size());
    }
    return m;
}

}  // namespace

void generate_one(IModelEngine& engine, SeqId seq, const RequestSpec& spec, ITokenSink& sink) {
    const std::vector<Token> prompt = engine.tokenize(spec.prompt, /*add_special=*/true);

    Usage usage;
    usage.prompt_tokens = static_cast<std::uint32_t>(prompt.size());

    engine.begin_sequence(seq, spec.sampling);

    const std::size_t holdback = max_stop_len(spec.stop);
    const auto        n_prompt = static_cast<Pos>(prompt.size());

    std::string text;        // all generated bytes
    std::size_t emitted = 0; // bytes handed to sink.on_text so far

    const auto flush_upto = [&](std::size_t upto) {
        if (upto > emitted) {
            sink.on_text(std::string_view(text).substr(emitted, upto - emitted));
            emitted = upto;
        }
    };

    // Prefill the whole prompt and sample the first token from its final position.
    GenStep cur{};
    {
        const BatchItem prefill{.seq = seq, .tokens = prompt, .pos0 = 0, .sample = true};
        const std::array<BatchItem, 1> batch{prefill};
        cur = engine.decode(batch).at(0);
    }
    Pos next_pos = n_prompt;  // position at which `cur.token` is decoded next

    FinishReason reason = FinishReason::kUnset;
    while (true) {
        if (cur.is_eog) {
            reason = FinishReason::kEos;
            break;
        }
        if (usage.completion_tokens >= spec.max_tokens) {
            reason = FinishReason::kMaxTokens;
            break;
        }

        text += engine.piece(cur.token);
        ++usage.completion_tokens;

        const std::size_t stop_at = earliest_stop(text, spec.stop);
        if (stop_at != std::string::npos) {
            flush_upto(stop_at);  // emit output up to the stop, nothing after
            reason = FinishReason::kStopString;
            break;
        }

        // Holdback flush: everything except the tail that could still start a stop.
        const std::size_t safe =
            (holdback > 0 && text.size() >= holdback - 1) ? text.size() - (holdback - 1)
            : (holdback > 0)                              ? 0
                                                          : text.size();
        flush_upto(safe);

        if (sink.cancelled()) {
            flush_upto(text.size());
            reason = FinishReason::kCancelled;
            break;
        }

        // Decode the accepted token to produce the next one.
        const Token tok = cur.token;
        const BatchItem item{
            .seq = seq, .tokens = std::span<const Token>(&tok, 1), .pos0 = next_pos, .sample = true};
        const std::array<BatchItem, 1> batch{item};
        cur = engine.decode(batch).at(0);
        ++next_pos;
    }

    // A clean finish flushes any held-back tail. A stop-string finish must not.
    if (reason == FinishReason::kEos || reason == FinishReason::kMaxTokens) {
        flush_upto(text.size());
    }

    engine.release_sequence(seq);
    sink.on_finish(reason, usage);
}

}  // namespace microvllm
